### ISSUE TITLE
Add wunderground language support

### ISSUE THREAD

**Issue by osos** [ThingPulse/esp8266-weather-station#17] opened 2016-01-28 21:58 UTC
Wunderground API provides language support:

http://www.wunderground.com/weather/api/d/docs?d=language-support&MR=1

like: http://api.wunderground.com/api/7ebc4762b61f6e42/forecast/**lang:FR**/q/France/Paris.jso

Would be a nice extension.

**Comment by stony2k** [comment] 2016-06-02 15:48
https://github.com/squix78/esp8266-weather-station/pull/25

Merged and can be closed

**Comment by osos** [comment] 2016-06-26 11:34
Works.

"Minor" issue however. It seem that special charactor like Danish ÆØÅ / æøå are treated wrong.

Sunday = Søndag or short Sun = Søn

Søn is sometimes truncated to "Sø" - so it seems that æøå are using 2 bytes from Wunderground ?

**Comment by squix78** [comment] 2016-09-08 13:03
Did you ever get around this? I think we added improved support for non base ASCII characters in the oled library, so it might be that the issue is now resolved...

**Comment by osos** [comment] 2016-11-12 06:00
Unfortunately this has not been solved by your update on the oled library.

Also suffering this on your color weatherstation. On the color version "æøå" are not displayed at all.

**Comment by totof60** [comment] 2017-05-18 07:24
The language didn't work for me in French for the "update forecast"
But it work with french canadian ( FC)
I added `const String WUNDERGRROUND_LANGUAGE2 = "FC";` in the setting.h
and `wunderground.updateForecast(WUNDERGRROUND_API_KEY, WUNDERGRROUND_LANGUAGE2, WUNDERGROUND_COUNTRY, WUNDERGROUND_CITY);`

**Comment by marcelstoer** [comment] 2019-01-22 21:10
[Weather Underground closed their existing API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api) for non-paying customers on 2018-12-31. After [they stopped issuing free API keys](https://thingpulse.com/hello-openweathermap-bye-bye-wunderground/) for low-volume personal use in May we migrated to OpenWeatherMap and [deprecated all WU code](https://github.com/ThingPulse/esp8266-weather-station#deprecation-notes) in this library.

We are now closing all WU-related issues and PRs.

**Closed by marcelstoer** 2019-01-22 21:10 UTC
