### ISSUE TITLE
Weather Underground GET request needs a timeout

### ISSUE THREAD

**Issue by AdySan** [ThingPulse/esp8266-weather-station#8] opened 2016-01-02 17:57 UTC
I think this is where the WeatherStation gets stuck sometimes. It just keeps waiting forever. I guess it would be a good idea to add a timeout here.

https://github.com/squix78/esp8266-weather-station/blob/master/WundergroundClient.cpp

```
 // This will send the request to the server
  client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: api.wunderground.com\r\n" +
               "Connection: close\r\n\r\n");
  while(!client.available()) {
    delay(1000);
  }
```

**Comment by Wolfi2000** [comment] 2016-01-03 11:26
I think it schould be done at all internet requests, not only while wunderground update.

**Comment by totof60** [comment] 2016-01-25 10:19
Ander L add a soluce for that , and it work for me 

Ander L say : 
Hi,
@Wolfgang : could try something like this:
// This will send the request to the server
client.print(String("GET ") + url + " HTTP/1.1\r\n" +
"Host: api.wunderground.com\r\n" +
"Connection: close\r\n\r\n");
int cntr=0;
while(!client.available()&& cntr < 3) {
cntr++;// Make 3 tries before quiting
delay(1000);
}
I've used something similar in other code for making sure the wifi is connected.

**Comment by AdySan** [comment] 2016-01-26 05:04
Cool, thanks. Just deployed this on my [WeatherBug](http://adityatannu.com/blog/post/2016/01/01/WeatherBug-ESP8266-WeatherStation-with-IFTTT-and-HomeKit-support.html), will report back how it goes. It generally seems to fail at night for me, works fine all day.

**Comment by stex2005** [comment] 2016-02-13 12:06
@AdySan have you solved the problem by adding the timeout?

I'm using the stuff concerning the Weather Station found here on GitHub. I'm improving the project by means of adding a MQTT communication to the EasyIoT cloud server in order to remotely control a Thermostat.
The MQTT part works fine, but sometimes (expecially during night) I'm having troubles with the OLED, which freezes and stops working (during the update to wunderground) until a RST.
It seems t I can't understand where's the problem.
 I've done some checks with WL_CONNECTED before requesting to wunderground, I've even added a timeout as suggested but it still freezes.

For a while I thought to add a softWDT to avoid this problem, in fact as I reset the node the system restart with any problems. Any idea?

WifiConnection code in loop:

` 
   if (WiFi.status() == WL_CONNECTED) {

    if (readyForThermostatUpdate && ui.getUiState().frameState == FIXED) {
      updateThermostat();
    }

    if (readyForWeatherUpdate && ui.getUiState().frameState == FIXED) {
      updateData(&display);
    }
  }
else{
   Serial.println("Disconnected.");
    WiFiConnect();
}

void WiFiConnect() {
  Serial.println("***************");
  Serial.print("Connecting to ");
  Serial.println(AP_SSID);
  WiFi.begin(AP_SSID, AP_PASSWORD);
  int counter = 0;
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    display.clear();
    display.drawString(64, 10, "Connecting to WiFi");
    display.drawXbm(46, 30, 8, 8, counter % 3 == 0 ? activeSymbole : inactiveSymbole);
    display.drawXbm(60, 30, 8, 8, counter % 3 == 1 ? activeSymbole : inactiveSymbole);
    display.drawXbm(74, 30, 8, 8, counter % 3 == 2 ? activeSymbole : inactiveSymbole);
    display.display();

    counter++;
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}`

Timeout code used:

`// This will send the request to the server
client.print(String("GET ") + url + " HTTP/1.1\r\n" +
"Host: api.wunderground.com\r\n" +
"Connection: close\r\n\r\n");
int cntr=0;
while(!client.available()&& cntr < 3) {
cntr++;// Make 3 tries before quiting
delay(1000);
}

**Comment by AdySan** [comment] 2016-02-13 17:08
@stex2005 Thanks for the pointer. Unfortunately adding the timeout hasn't helped as you observed too. I never really considered that the OLED could be freezing. I don't thing it's a problem with the OLED library, since I have other projects using it which are running flawlessly. Perhaps something to do with the UI part of the library.

**Comment by kentaylor** [comment] 2016-07-04 14:46
This is an ongoing problem that I experience regularly and is also reported in https://github.com/squix78/esp8266-weather-station/issues/36 . @stex2005 [reports](https://github.com/squix78/esp8266-weather-station/issues/8#issuecomment-183655081) and @AdySan  [reports](https://github.com/squix78/esp8266-weather-station/issues/8#issuecomment-183704307) that adding a timeout doesn't fix it, presumably because the call to [client.available()] (https://github.com/kentaylor/esp8266-weather-station/blob/master/ThingspeakClient.cpp#L42) is not returning.

I don't know the solution but can provide some data. I'm confident it doesn't occur if the internet connection is good and the server to which it connects is working correctly. The evidence is that I have one device on a flaky network at https://thingspeak.com/channels/126118 and it fails much more often than one on a good network at home. The device on the flaky network sometimes fails on the Updating time... screen which I haven't seen on the good network. Thingspeak is flaky and fails in different ways. Most of the time this shows up as a gap in the data for both device installations. It can also show up in both devices failing at the Updating thingspeak... screen at the same time. I've recorded the [connection times](https://docs.google.com/spreadsheets/d/1ORIPM0SaMFpoDUlFn8f1AlrvnIwCyJjLfRhxTEpOwd0/edit?usp=sharing) of one simultaneous freeze failure on both devices. The simultaneous identical failure on different networks must be associated with an incorrect response from the Thingspeak server that the ESP8266 can not handle.

Interestingly Thingspeak is called in 2 places in the code, [here](https://github.com/kentaylor/esp8266-weather-station/blob/master/examples/WeatherDHT22ThreeScreensWiFiManager/WeatherDHT22ThreeScreensWiFiManager.ino#L768) and [here](https://github.com/kentaylor/esp8266-weather-station/blob/master/ThingspeakClient.cpp#L42) . One is called 5 times more often than the other but the failure always occurs in the code called least often. The difference is that one call waits for a response and continues to call client.available() while it waits while the other calls client.available() once and moves on. So it is something to do with waiting for a response when the response has errors and getting stuck in the client.available() function. The client.available() function maps to a call to the Espressif library at https://github.com/esp8266/Arduino/blob/633e48f3aec5f1c3c11d4498fc90d378d49e6e9f/libraries/ESP8266WiFi/src/include/ClientContext.h#L208 .

**Comment by kentaylor** [comment] 2016-07-21 20:34
Still getting stuck and able to observe that it was stuck [here] (https://github.com/kentaylor/esp8266-weather-station/blob/77891b2892f8cc2d72c3ffd1d6bf90be56fee015/ThingspeakClient.cpp#L32) on one occasion.

Currently the weather station library uses the WiFiClient library for accessing web services. This requires that the http processing logic and request format be constructed in code. There is also a higher level HTTPClient library that could be used for these interactions.

**Comment by squix78** [comment] 2016-09-08 12:44
Hi Ken. What is the situation for you on this issue? Did your fix solve it? I am running now my weather station for several weeks without need for manual restart...

**Comment by kentaylor** [comment] 2016-09-25 12:55
I like the idea of using the HTTPClient library. This accesses web services at a higher level of abstraction than the WiFiClient library so for that reason alone I'd recommend the changes in the commit at https://github.com/kentaylor/esp8266-weather-station/commit/f4bdc9630a95ab6425d895cd8a26ebec4fb66f3a. 

Since having made that change I haven't seen a failure but I'm not sure if the HTTPClient library has fixed the problem. I previously had a device on a flaky network so I saw the problem often (every few days). That network is now fixed so I can't be sure if the code change helped. I have only seen the problem rarely (less than once per month) on a good network. I've also seen it when Thingspeak gets overloaded and Thingspeak responses become flaky but that was only once. If that happens, every weather station everywhere will fail at roughly the same time and have to be rebooted.

**Comment by kentaylor** [comment] 2016-10-27 23:13
The HTTPClient library has not fixed the problem. I now have a few devices on a Telco WiFi dongle and some have experienced the hanging problem again. I expect that is because TELCO networks are flaky at times.

This means that the problem is not in the Weather Station code and in particular is not related to the way the weather station library uses the WiFiClient library for accessing web services. The problem is further down the stack somewhere within the HTTP or TCP/IP handling.

I've seen it in other applications that use HTTP as well but never in applications that use UDP. If the device can not establish a HTTP connection it will be OK but if it establishes the connection it becomes susceptible to hanging when connectivity is lost part way through the transmission. It will continue to wait for data that the server will never send, even after network connectivity is reestablished. With UDP it doesn't wait which is probably why UDP doesn't cause hanging.

**Closed** 2018-05-06 21:28 UTC
